//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CursoNetEntities : DbContext
    {
        public CursoNetEntities()
            : base("name=CursoNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Alumno_Asignatura> Alumno_Asignatura { get; set; }
        public virtual DbSet<Asignatura> Asignatura { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Carrera_Asignatura> Carrera_Asignatura { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
