//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id { get; set; }
        public string login { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string correo_electronico { get; set; }
        public System.DateTime fecha_proceso { get; set; }
    }
}
